# Generated by Django 6.0.2 on 2026-02-18 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_country_profile_province_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.TextField()),
                ('pincode', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.country')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.province')),
            ],
        ),
    ]
