# Generated by Django 6.0.2 on 2026-02-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_address_profile_addresses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='addresses',
            new_name='address_set',
        ),
    ]
