expired = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMzkzOTM5LCJpYXQiOjE3NzEzOTM5MjksImp0aSI6IjJhZWY1NGEyNDJjOTRmNTBiMzMyZTE4NGIyMzNmNjg0IiwidXNlcl9pZCI6IjMifQ.deSwKdieXPCoy9vDPQ2EHrjarZjHlUAv2kHb4dZzYu0"
new_token = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMzkzOTM5LCJpYXQiOjE3NzEzOTM5MjksImp0aSI6IjJhZWY1NGEyNDJjOTRmNTBiMzMyZTE4NGIyMzNmNjg0IiwidXNlcl9pZCI6IjMifQ.deSwKdieXPCoy9vDPQ2EHrjarZjHlUAv2kHb4dZzYu0"
retry = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMzkzOTM5LCJpYXQiOjE3NzEzOTM5MjksImp0aSI6IjJhZWY1NGEyNDJjOTRmNTBiMzMyZTE4NGIyMzNmNjg0IiwidXNlcl9pZCI6IjMifQ.deSwKdieXPCoy9vDPQ2EHrjarZjHlUAv2kHb4dZzYu0" 

print(expired == new_token)
print(new_token == retry)