"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os
import base64

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'secret-key') 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

PROD_HOST = os.environ.get('PROD_HOST', 'localhost')

ALLOWED_HOSTS = ['localhost', PROD_HOST]
CORS_ALLOWED_ORIGINS = [
    'http://localhost',
    f'http://{PROD_HOST}',
    f'https://{PROD_HOST}'
]
CSRF_TRUSTED_ORIGINS = [
    'http://localhost',
    f'http://{PROD_HOST}',
    f'https://{PROD_HOST}'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',

    'accounts',
    'products',
    'cart',
    'orders',
    'location',
    'analytics'
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get('DB_NAME', "shop_db"),
        "USER": os.environ.get('DB_USER', "postgres"),
        "PASSWORD": os.environ.get('DB_PASSWORD', "postgres"),
        "HOST": os.environ.get('DB_HOST', "localhost"),  # or container name if using docker-compose
        "PORT": os.environ.get('DB_POST', "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]

AUTHENTICATION_BACKENDS = [
    # this is for authentication in admin panel which sends email with key 'username'
    'django.contrib.auth.backends.ModelBackend',
    
    # to authenticate with email with key also being 'email'
    'accounts.backends.CustomAuthBackend', 
]

AUTH_USER_MODEL = 'accounts.User'

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static/'
STATICFILES_STORAGE= "whitenoise.storage.CompressedManifestStaticFilesStorage"

REST_FRAMEWORK = {

}

PRIVATE_KEY = base64.b64decode(
    os.getenv("JWT_PRIVATE_KEY_B64")
).decode("utf-8")

PUBLIC_KEY = base64.b64decode(
    os.getenv("JWT_PUBLIC_KEY_B64")
).decode("utf-8")

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': 'RS256',
    'SIGNING_KEY': PRIVATE_KEY,
    'VERIFYING_KEY': PUBLIC_KEY,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id', # which field on the User model uniquely defines the user
    'USER_ID_CLAIM': 'user_id', # what key name to use inside the jwt payload
}

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND')

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'test_email@mail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'test_password')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

AUTH0_DOMAIN = os.environ.get("AUTH0_DOMAIN", "your-tenant.us.auth0.com")
AUTH0_CLIENT_ID = os.environ.get("AUTH0_CLIENT_ID", "")
AUTH0_CLIENT_SECRET = os.environ.get("AUTH0_CLIENT_SECRET", "")
AUTH0_CALLBACK_URL = os.environ.get(
    "AUTH0_CALLBACK_URL",
    "http://localhost:8000/api/accounts/oauth/token/",
)
AUTH0_FRONTEND_SUCCESS_URL = os.environ.get(
    "AUTH0_FRONTEND_SUCCESS_URL",
    "http://localhost:5173/login",
)
AUTH0_FRONTEND_FAILURE_URL = os.environ.get(
    "AUTH0_FRONTEND_FAILURE_URL",
    "http://localhost:5173/login",
)
AUTH0_SCOPE = os.environ.get("AUTH0_SCOPE", "openid profile email")
API_AUDIENCE = os.environ.get("API_AUDIENCE", "https://my-api.example.com")

MIXPANEL_PROJECT_TOKEN = os.environ.get("MIXPANEL_PROJECT_TOKEN", "")
MIXPANEL_TRACK_URL = os.environ.get(
    "MIXPANEL_TRACK_URL",
    "https://api.mixpanel.com/track",
)

print(f'AUTH0_CALLBACK_URL: {AUTH0_CALLBACK_URL}')