# Generated by Django 6.0.2 on 2026-02-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='state',
            new_name='province',
        ),
    ]
