# Generated by Django 6.0.2 on 2026-02-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.ManyToManyField(to='accounts.address'),
        ),
    ]
