# Generated by Django 6.0.2 on 2026-02-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_addresses_profile_address_set'),
        ('orders', '0003_alter_order_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address_set',
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='province',
            name='country',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
