FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

RUN apt-get update && apt-get install -y netcat-openbsd

COPY . /app
RUN chmod +x /app/scripts/start_django.sh

EXPOSE 8000

CMD ["sh", "/app/scripts/start_django.sh"]
